import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function adjustGender(text: string, gender: "m" | "f") {
  if (gender === 'f') {
    return text
      .replace(/התמקד\/י/g, "התמקדי")
      .replace(/עקוב\/י/g, "עקבי")
      .replace(/קח\/י/g, "קחי")
      .replace(/שחרר\/י/g, "שחררי")
      .replace(/מצא\/ו/g, "מצאי")
      .replace(/הקשב\/י/g, "הקשיבי")
      .replace(/שים\/י/g, "שימי")
      .replace(/נסה\/י/g, "נסי")
      .replace(/קרב\/י/g, "קרבי")
      .replace(/בחר\/י/g, "בחרי")
      .replace(/התאמ\/י/g, "התאימי")
      .replace(/התכונן\/י/g, "התכונני")
      .replace(/הרכב\/י/g, "הרכיבי")
      .replace(/תרגל\/י/g, "תרגלי")
      .replace(/רוצה\/ה/g, "רוצה")
      .replace(/מבין\/ה/g, "מבינה")
      .replace(/מעבד\/ת/g, "מעבדת")
      .replace(/המטפל\/ת/g, "המטפלת")
      .replace(/מרגיש\/ה/g, "מרגישה")
      .replace(/מוכן\/ה/g, "מוכנה")
      .replace(/ברוך\/ה/g, "ברוכה")
      .replace(/הבא\/ה/g, "הבאה")
      .replace(/בוא\/י/g, "בואי")
      .replace(/שאף\/י/g, "שאפי")
      .replace(/נשוף\/י/g, "נשפי")
      .replace(/החזק\/י/g, "החזיקי")
      .replace(/הרפה\/י/g, "הרפי")
      .replace(/פתח\/י/g, "פתחי")
      .replace(/עצום\/צי/g, "עצמי")
      .replace(/עצום\/ה/g, "עצומה")
      .replace(/שתרגיש\/י/g, "שתרגישי")
      .replace(/מתקשה\/ה/g, "מתקשה")
      .replace(/בחר\/יי/g, "בחרי")
      .replace(/שתרגיש\/ה/g, "שתרגישי")
      .replace(/תרצה\/י/g, "תרצי")
      .replace(/הוסיפי\/ה/g, "הוסיפי")
      .replace(/הוסף\/י/g, "הוסיפי")
      .replace(/תאר\/י/g, "תארי")
      .replace(/שאת\/ה/g, "שאת")
      .replace(/את\/ה/g, "את")
      .replace(/שתחזור\/י/g, "שתחזרי")
      .replace(/שמור\/י/g, "שמרי");
  }
  return text
    .replace(/התמקד\/י/g, "התמקד")
    .replace(/עקוב\/י/g, "עקוב")
    .replace(/קח\/י/g, "קח")
    .replace(/שחרר\/י/g, "שחרר")
    .replace(/מצא\/ו/g, "מצא")
    .replace(/הקשב\/י/g, "הקשב")
    .replace(/שים\/י/g, "שים")
    .replace(/נסה\/י/g, "נסה")
    .replace(/קרב\/י/g, "קרב")
    .replace(/בחר\/י/g, "בחר")
    .replace(/התאמ\/י/g, "התאם")
    .replace(/התכונן\/י/g, "התכונן")
    .replace(/הרכב\/י/g, "הרכב")
    .replace(/תרגל\/י/g, "תרגל")
    .replace(/רוצה\/ה/g, "רוצה")
    .replace(/מבין\/ה/g, "מבין")
    .replace(/מעבד\/ת/g, "מעבד")
    .replace(/המטפל\/ת/g, "המטפל")
    .replace(/מרגיש\/ה/g, "מרגיש")
    .replace(/מוכן\/ה/g, "מוכן")
    .replace(/ברוך\/ה/g, "ברוך")
    .replace(/הבא\/ה/g, "הבא")
    .replace(/בוא\/י/g, "בוא")
    .replace(/שאף\/י/g, "שאף")
    .replace(/נשוף\/י/g, "נשוף")
    .replace(/החזק\/י/g, "החזק")
    .replace(/הרפה\/י/g, "הרפה")
    .replace(/פתח\/י/g, "פתח")
    .replace(/עצום\/צי/g, "עצום")
    .replace(/עצום\/ה/g, "עצום")
    .replace(/שתרגיש\/י/g, "שתרגיש")
    .replace(/מתקשה\/ה/g, "מתקשה")
    .replace(/בחר\/יי/g, "בחר")
    .replace(/שתרגיש\/ה/g, "שתרגיש")
    .replace(/תרצה\/י/g, "תרצה")
    .replace(/הוסיפי\/ה/g, "הוסף")
    .replace(/הוסף\/י/g, "הוסף")
    .replace(/תאר\/י/g, "תאר")
    .replace(/שאת\/ה/g, "שאתה")
    .replace(/את\/ה/g, "אתה")
    .replace(/שתחזור\/י/g, "שתחזור")
    .replace(/שמור\/י/g, "שמור");
}

